# Generated by Django 4.2.4 on 2023-08-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='iamge',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
