# Generated by Django 4.2.4 on 2023-08-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_task_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='iamge',
            new_name='image',
        ),
    ]
