# Generated by Django 4.2.4 on 2023-08-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0004_alter_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
